### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by tristanwietsma** [gogo/gogo.github.io#4]
https://github.com/gogo/gogo.github.io/blob/master/index.html#L38

this renders incorrectly (see lower left corner):

![screen shot 2015-01-14 at 8 59 02 pm](https://cloud.githubusercontent.com/assets/1371478/5751870/40fa0490-9c30-11e4-9039-1354cb96cceb.png)

**Comment by awalterschulze** [comment]
Thank you :)
I just fixed it.
